### ISSUE TITLE
Implement selective convolution in 1D CNN

### ISSUE THREAD

**Issue by QueeneTam** [jh-jeong/selective-convolution#2]
Thanks for your great work! It gives me some thought about my work and I am going to use it to my 1D CNN. Can you please tell me where should I notice to modify? The shape of 2D CNN and 1D CNN is queit different.

**Comment by jh-jeong** [comment]
Hi, @QueeneTam, thanks for your interest. 

I think you can modify most of the components of `SelectiveConv2d` in a straightforward way, e.g., you may need to change:
- BatchNorm2d -> BatchNorm1d 
- _distributed_channel(): you should adapt (H,W) -> L

One issue I guess is that `affine_grid` and `grid_sample` are currently hard to directly adapt to 1d version afaik, as their implementations currently supports only for 4d inputs. They both are for training "shifting" parameters, and you may not need them if it is ok to use our shifting components with random parameters without training: in case of 2d conv, we have observed that this "random shifting" also works fine.

**Comment by QueeneTam** [comment]
> affine_grid

Thanks for you kind-hearted reply, and I will try my best to make it work for my experiment.

**Comment by QueeneTam** [comment]
> Hi, @QueeneTam, thanks for your interest.
> 
> I think you can modify most of the components of `SelectiveConv2d` in a straightforward way, e.g., you may need to change:
> 
> * BatchNorm2d -> BatchNorm1d
> * _distributed_channel(): you should adapt (H,W) -> L
> 
> One issue I guess is that `affine_grid` and `grid_sample` are currently hard to directly adapt to 1d version afaik, as their implementations currently supports only for 4d inputs. They both are for training "shifting" parameters, and you may not need them if it is ok to use our shifting components with random parameters without training: in case of 2d conv, we have observed that this "random shifting" also works fine.

Thanks for you kind-hearted reply, and I will try my best to make it work for my experiment.
